mapinfo.o: mapinfo.c mapinfo.h
packet.o: packet.c packet.h
requestloop.o: requestloop.c requestloop.h
chat_message.o: chat_message.c chat_message.h
shared.o: shared.c shared.h
main.o: main.c main.h
queue_chat.o: queue_chat.c queue_chat.h
sendpacket.o: sendpacket.c sendpacket.h
send_map_file.o: send_map_file.c send_map_file.h
queue_block.o: queue_block.c queue_block.h
lib_md5.o: lib_md5.c lib_md5.h
